### ISSUE TITLE
Need help setting up magic link with Grafana

### ISSUE THREAD

**Issue by raspreet-vunet** [p2-inc/keycloak-magic-link#58]
I'm facing a weird issue when trying to use magic links with Grafana. When I click on the magic link Grafana gives me a "missing saved state" exception (see screenshot below)

![image](https://github.com/p2-inc/keycloak-magic-link/assets/113003295/2f343ea7-2536-4d7b-a067-51abcfda6518)

There is nothing useful in the grafana logs and the weird thing is that the authentication has happened successfully, even with this error. If I open the root url in the browser now, I find myself logged in with the desired user.

Relevant config from the grafana setup I'm using for testing this
```toml
[auth]
disable_login_form = true
oauth_auto_login = true

[auth.generic_oauth]
allow_sign_up = true
api_url = "<keycloak_server_url>/auth/realms/<realm>/protocol/openid-connect/userinfo"
auth_url = "/auth/realms/<realm>/protocol/openid-connect/auth"
client_id = "<redacted>"
client_secret = "<redacted>"
enabled = true
login_attribute_path = "preferred_username"
name = "Keycloak"
scopes = "openid email"
token_url = "<keycloak_server_url>/auth/realms/<realm>/protocol/openid-connect/token
```

I'll be happy to provide any other info. Thanks in advance!
